version: '3'
services:
  go-app:
    build: .
    image: go-echo-app
    container_name: go-echo-app
    tty: true
    ports:
      - 1324:1324
    volumes:
      - ./api:/go/src/api
      - ./go.mod:/go/src/go.mod
      - ./go.sum:/go/src/go.sum

